res = [128,720] # Resolutions to export at
reverse = true # If true, generate flipped versions (as well as normal versions)
webp = false # If true, create animated emojis as webp files as well as apngs


palette.ying = {} # Default palette, so nothing is changed!

[palette.mint]
	main = "#9f8"
	eye = "#cff"
	line = "#131"
	dark = "#3b4"
	lid =  "#474"
	hand = "#474"
	tongue = "#141"
	hair = "#262"
	tail = "#262"
	heart_inner = "#0f0"
	heart_outer = "#131"
	show_all = true
	p2_hair = "#0000"
	p2_tail = "#0000"

[palette.p2]
    main=  "#5fd3bc" 
    eye =  "#ccfefe" 
    line = "#165044" 
    dark = "#389482" 
    lid =  "#2ca089" 
    hand = "#3a685f" 
    tongue="#8B305C" 
    hair = "#345612" 
    tail = "#456723" 
    heart_inner="#00c3ff"
    heart_outer="#0080a2"
	p2_main=  "#ffcb4c"
    p2_eye =  "#fefefe"
    p2_line = "#65471b"
    p2_dark = "#f19020"
    p2_lid =  "#d19020"
    p2_hand = "#a18020"
    p2_tongue="#ff5678"
    p2_hair = "#123456"
    p2_tail = "#234567"
    p2_heart_inner="#ff5555"
    p2_heart_outer="#b10020"

[palette.myno]
	main="#e4d9b9"
	eye = "#cdebfd"
	line = "#880056"
	dark = "#a99f8b"
	lid = "#a99f8b"
	hand = "#a99f8b"
	hair = "#913fef"
	tail = "#913fef"
	tongue = "#ff66aa"
	heart_inner = "#fc037b"
	heart_outer = "#94017b"
	show_all = true
	p2_hair = "#0000"
	p2_tail = "#0000"